### PR TITLE
Fix missing complianceStatus in certificate request and key DTOs

### LINKED ISSUE #1394: CertificateRequestDto required property ComplianceStatus not provided
In version 2.17.0, the `CertificateRequestDto` required property `ComplianceStatus` is not provided in response when asking for certificate details.

### PR DESCRIPTION
**Pull request by klaraf755**
Fixes #1394

### CODE REVIEW

File: src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java [hunk 1]
```diff
@@ -115,15 +116,32 @@ public KeyDto mapToDto() {
...
+    ComplianceStatus getComplianceStatus() {
+        List<ComplianceStatus> statuses = items.stream().map(CryptographicKeyItem::getComplianceStatus).toList();
+        if (statuses.contains(ComplianceStatus.FAILED)) {
+            return ComplianceStatus.FAILED;
+        } else if (statuses.contains(ComplianceStatus.NOK)) {
+            return ComplianceStatus.NOK;
+        } else if (statuses.contains(ComplianceStatus.NA)) {
+            return ComplianceStatus.NA;
+        } else if (statuses.contains(ComplianceStatus.NOT_CHECKED)) {
+            return ComplianceStatus.NOT_CHECKED;
```
[the remark this answers is not in the document]
Comment (klaraf755) [reply src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java]: it is not typical for key to exist to without items, but I will add the checks for completeness

File: src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java [hunk 2]
```diff
@@ -115,15 +116,41 @@ public KeyDto mapToDto() {
...
     }
 
+    ComplianceStatus getComplianceStatus() {
+        if (items.isEmpty()) {
+            return ComplianceStatus.NOT_CHECKED;
+        }
+        List<ComplianceStatus> statuses = items.stream()
+                .map(CryptographicKeyItem::getComplianceStatus)
+                .filter(Objects::nonNull)
+                .toList();
```
Comment (lubomirw) [inline src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java:130]: NOK should take priority over FAILED in compliance status aggregation

The current priority order is FAILED > NOK > NA > NOT_CHECKED > OK, but `ComplianceSubjectHandler#calculateComplianceStatus(ComplianceResultRulesDto)` establishes that NOK (non-compliant) is the most severe compliance finding. FAILED indicates an operational error during the compliance check, while NOK is a definitive compliance verdict. If any key item is NOK and another is FAILED, the aggregated status should be NOK — reporting FAILED would hide the actual non-compliance.

**Review by lubomirw — CHANGES_REQUESTED** [review]
Code review: 1 issue(s) found.

File: src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java (hunk 2 above)
Comment (klaraf755) [reply src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java:130]: Switched the check

File: src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java [hunk 3]
```diff
@@ -115,15 +116,41 @@ public KeyDto mapToDto() {
         }
         dto.setItems(getKeyItemsSummary());
         dto.setAssociations((items.size() - 1) + certificates.size() + altCertificates.size());
+        dto.setComplianceStatus(getComplianceStatus());
         return dto;
     }
 
+    ComplianceStatus getComplianceStatus() {
```
Comment (lubomirw) [inline src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java]: Method can be private

**Review by lubomirw — CHANGES_REQUESTED** [review]

File: src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java (hunk 3 above)
Comment (klaraf755) [reply src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java]: fixed

**Review by lubomirw — APPROVED** [review]
