### PR TITLE
Optimize database performance of getting a certificate chain

### LINKED ISSUE #1411: Certificates - Certificate Chain: Excessive DB queries during chain retrieval (40–60 queries for 5-cert chain)
## Description
The certificate chain retrieval logic issues an excessive number of database queries — approximately **40–60 queries for a chain of only 5 certificates**. This is a classic N+1 query pattern: each certificate in the chain triggers individual lookups for the issuer certificate, trust anchor status, and/or related metadata, rather than resolving the full chain in a single set-based or recursive operation. At production scale, this degrades API response times and increases database load proportionally to chain length and request concurrency.

## Steps to Reproduce
1. Ensure a certificate chain of ~5 certificates is present in the system (leaf → intermediate(s) → root)
2. Open the detail view of a leaf certificate (e.g. via `GET /api/v1/certificates/{uuid}` or the **Certificate Detail** page in the administrator UI)
3. Observe the **Certificate Chain** section loading
4. Monitor database query count via SQL logging (e.g. `spring.jpa.show-sql=true`) or an APM/profiling tool

## Expected Result
- The full certificate chain is resolved in a small, fixed number of queries (ideally a single recursive CTE / `WITH RECURSIVE` query, or at most one query per distinct table involved)
- Response time does not scale linearly with chain length

## Actual Result
- Approximately 40–60 individual SQL queries are issued to retrieve a 5-certificate chain
- Each certificate in the chain triggers multiple independent lookups (issuer resolution, metadata, status, etc.)
- Performance degrades linearly with chain depth and is compounded under concurrent load

## Environment
Frontend (czertainly-administrator):

ILM Core:
Commit:
Branch:
Build time:

Client:
- OS:
- Browser:

### PR DESCRIPTION
**Pull request by ivosh**
For 5-certificate chain, reduces the number of JDBC queries from 56 to mere 3.

### CODE REVIEW

File: src/main/java/com/czertainly/core/dao/entity/Certificate.java [hunk 1]
```diff
@@ -32,6 +32,38 @@
...
+@NamedEntityGraph(
+        name = "Certificate.chainAssociations",
+        attributeNodes = {
+                @NamedAttributeNode("certificateContent"),
+                @NamedAttributeNode(value = "key",      subgraph = "key-items"),
+                @NamedAttributeNode(value = "altKey",   subgraph = "alt-key-items"),
+                @NamedAttributeNode("groups"),
+                @NamedAttributeNode("owner"),
+                @NamedAttributeNode(value = "raProfile", subgraph = "ra-profile-authority"),
+                @NamedAttributeNode("certificateRequestEntity"),
```
[the remark this answers is not in the document]
Comment (ivosh) [reply src/main/java/com/czertainly/core/dao/entity/Certificate.java]: Fixed.

File: src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java [hunk 2]
```diff
@@ -35,6 +35,14 @@ public interface CertificateRepository extends SecurityFilterRepository<Certific
     @EntityGraph(attributePaths = {"certificateContent", "key", "key.items", "groups", "owner", "altKey", "altKey.items", "raProfile"})
     List<Certificate> findWithAssociationsByUuidInOrderByCreatedDesc(List<UUID> uuids);
 
+    /** Fetches a single certificate with all associations required by {@link Certificate#mapToDto()}. */
+    @EntityGraph("Certificate.chainAssociations")
+    Optional<Certificate> findChainWithAssociationsByUuid(UUID uuid);
+
+    /** Batch variant used when preloading a list of chain ancestors in one round-trip. */
```
[the remark this answers is not in the document]
Comment (ivosh) [reply src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java]: Fixed.

File: src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java [hunk 3]
```diff
@@ -996,13 +1026,16 @@ public CertificateValidationResultDto getCertificateValidationResult(SecuredUUID
...
+
+    private boolean isSelfSigned(X509Certificate x509Certificate, UUID certificateUuid) throws CertificateException {
         // we check the signature with the certificate public key
-        X509Certificate x509Certificate = getX509(certificate.getCertificateContent().getContent());
         try {
             x509Certificate.verify(x509Certificate.getPublicKey());
             return true;
         } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
-            logger.debug("Unable to verify if the certificate {} is self-signed: {}", certificate.getUuid(), e.getMessage());
+            logger.debug("Unable to verify if the certificate {} is self-signed: {}",  certificateUuid, e.getMessage());
```
[the remark this answers is not in the document]
Comment (ivosh) [reply src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java]: Fixed.

File: src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java [hunk 4]
```diff
@@ -996,13 +1026,16 @@ public CertificateValidationResultDto getCertificateValidationResult(SecuredUUID
```
Comment (lubomirw) [inline src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java:995]: The comment says "return an incomplete chain" but the `for` loop continues iterating. This could produce an incorrect chain with a gap. The old `while` loop exited naturally because it checked `getIssuerCertificateUuid() != null` each iteration after clearing the FK. Aren't we missing here `break` or `return`?

File: src/test/java/com/czertainly/core/service/CertificateValidationTest.java [hunk 5]
```diff
@@ -626,6 +626,96 @@ private DistributionPoint[] createCrlDistributionPoints(List<String> urls) {
...
+        Assertions.assertEquals(withoutEnd.getCertificates().size() + 1, withEnd.getCertificates().size());
+        // The first certificate returned must be the end certificate
+        Assertions.assertEquals(chainIncompleteCertificate.getSubjectDn(), withEnd.getCertificates().get(0).getSubjectDn());
+        // Chain-completeness judgement must be consistent regardless of withEndCertificate flag
+        Assertions.assertEquals(withoutEnd.isCompleteChain(), withEnd.isCompleteChain());
+    }
+
+    @Test
+    void testGetCertificateChainThreeLevelWithEndCertificate() throws Exception {
+        // Build a three-level chain: root CA → intermediate CA → end entity
```
Comment (lubomirw) [inline src/test/java/com/czertainly/core/service/CertificateValidationTest.java:667]: The new recursive CTE query `findCertificateChainUuids` has cycle detection (`NOT (c.uuid = ANY(chain.path))`) and a `maxDepth` safety cap — both are important safety mechanisms against malformed data. Consider adding a test that creates a circular issuer reference (e.g. A→B→A) and verifies the chain query terminates correctly without an infinite loop or exceeding the depth limit.

**Review by lubomirw — CHANGES_REQUESTED** [review]
Code review: 2 issue(s) found.

File: src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java (hunk 4 above)
Comment (ivosh) [reply src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java:995]: Fixed.

File: src/test/java/com/czertainly/core/service/CertificateValidationTest.java (hunk 5 above)
Comment (ivosh) [reply src/test/java/com/czertainly/core/service/CertificateValidationTest.java:667]: Fixed.

**Review by lubomirw — APPROVED** [review]
